version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  windows-build:
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    steps:
      - checkout
      - run: go build -o hello-world-windows src/main.go # build the go library.
      - run:
          name: Compile for Mac
          command: go build -o hello-world-mac src/main.go
          environment:
            GOOS: darwin
            GOARCH: amd64
      - run:
          name: Compile for Linux
          command: go build -o hello-world-linux src/main.go
          environment:
            GOOS: linux
            GOARCH: amd64
      - run: mkdir -p "C:\tmp\bin"
      - run:
          name: Move compiled binaries into the temporary folder.
          command: |
            Move-Item -Path .\hello-world-mac -Destination C:\tmp\bin
            Move-Item -Path .\hello-world-linux -Destination C:\tmp\bin
            Move-Item -Path .\hello-world-windows -Destination C:\tmp\bin
      - persist_to_workspace:
          root: C:\tmp
          paths:
            - bin

  mac-test:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.3.0 # indicate our selected version of Xcode
    steps: # a series of commands to run
      - attach_workspace:
          at: /tmp
      - run:
          name: View attached workspace results and make bins executable.
          command: |
            cd /tmp/bin
            chmod +x ./hello-world-mac
            ls -la
      - run:
          name: Test OS X binary.
          command: |
            cd /tmp/bin
            if ./hello-world-mac | grep -q 'Hello world from: darwin'; then
              echo "Mac binary successfully run"
              exit
            else
              echo "Mac binary not successfully run"
              exit 1
            fi

  linux-test:
    docker:
      - image: cimg/base:2020.01
    steps: # a series of commands to run
      - attach_workspace:
          at: /tmp
      - run:
          name: View attached workspace results and make bins executable.
          command: |
            cd /tmp/bin
            chmod +x ./hello-world-linux
            ls -la
      - run:
          name: Test Linux binary.
          command: |
            cd /tmp/bin
            if ./hello-world-linux | grep -q 'Hello world from: linux'; then
              echo "Linux binary successfully run"
              exit
            else
              echo "Linux binary not successfully run"
              exit 1
            fi

workflows:
  version: 2
  build-multiplatform:
    jobs:
      - windows-build
      - linux-test:
          requires:
            - windows-build
      - mac-test:
          requires:
            - windows-build
