version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  windows-build:
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    steps:
      - checkout
      - run: go build -o hello-world-windows src/main.go # build the go library.
      - run:
          name: Compile for Mac
          command: go build -o hello-world-mac src/main.go
          environment:
            GOOS: darwin
            GOARCH: amd64
      - run:
          name: Compile for Linux
          command: go build -o hello-world-linux src/main.go
          environment:
            GOOS: linux
            GOARCH: amd64
      - run: mkdir -p "C:\tmp\bin"
      - run:
          name: Move compiled binaries into the temporary folder.
          command: |
            Move-Item -Path .\hello-world-mac -Destination C:\tmp
            Move-Item -Path .\hello-world-linux -Destination C:\tmp
            Move-Item -Path .\hello-world-windows -Destination C:\tmp
      - persist_to_workspace:
          root: C:\tmp
          paths:
            - bin

  mac:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.3.0 # indicate our selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - attach_workspace:
          at: /tmp
      - run:
          name: Look at workspace
          command: |
            echo "------ workspace tmp is ----------"
            ls -la /tmp
            ls -la /tmp/bin
            cd /tmp
            ls
            cd bin
            ls

            # cd /tmp/workspace
            # ls -la

workflows:
  version: 2
  build-multiplatform:
    jobs:
      - windows-build
      - mac:
          requires:
            - windows-build
